# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger: none

variables:
  #- group: toolkit-test-pack
  - group: toolkit-build-version-configuration

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: $(WindowsVmImage)
      steps:
      - template: ./steps/checkCode.yml

    - job: BuildTestPack
      pool:
        vmImage: $(VmImage)
      steps:
      - template: ./steps/build.yml
        parameters:
          targetBuildFramework: 'net8.0'
          unitTest : false

      - template: ./steps/versionVariables.yml
      
      - template: ./steps/pack.yml
        parameters:
          PackageArtifactName: ReleasePackages
          Version: $(SetVariables.ReleaseVersion)
          AssemblyVersion: $(ReleaseAssemblyVersion)
          FileVersion: $(ReleaseFileVersion)

      - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AppliedOpenSourceTools'))}}:
        - template: ./steps/pack.yml
          parameters:
            PackageArtifactName: PrereleasePackages
            Version: $(SetVariables.PrereleaseVersion)
            AssemblyVersion: $(PrereleaseAssemblyVersion)
            FileVersion: $(PrereleaseFileVersion)

    # Run release only on manual build (Build.Reason is sometimes blank here) against the internal project. Run for both release and pre-release
  - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AppliedOpenSourceTools'))}}:
    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: PrereleasePackages
        DevOpsFeedID: AppliedOpenSourceTools/AzureHealthDataServicesToolkitInternal
        IsPrerelease: true

    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: ReleasePackages
        DevOpsFeedID: AppliedOpenSourceTools/AzureHealthDataServicesToolkitInternal
        IsPrerelease: false