parameters:
  unitTest: true
  componentGovernance: true
  targetBuildFramework: ''

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-incremental -p:ContinuousIntegrationBuild=true -warnaserror -f ${{parameters.targetBuildFramework}}'
    projects: '**/Microsoft.AzureHealth.DataServices.*.csproj'
  displayName: 'Build toolkit projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-incremental -p:ContinuousIntegrationBuild=true -warnaserror -f ${{parameters.targetBuildFramework}}'
    projects: '**/samples/**/*.csproj'
  displayName: 'Build samples projects'

- ${{ if eq(parameters.componentGovernance, 'true') }}:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: true

- ${{ if eq(parameters.unitTest, 'true') }}:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--no-build --configuration $(buildConfiguration) -f ${{parameters.targetBuildFramework}}'
      publishTestResults: true
      projects: '**/Microsoft.AzureHealth.DataServices.Tests.csproj'
    displayName: 'Run all tests'
    env:
      AZURE_TENANT_ID: $(proxy-tenant-id)
      AZURE_CLIENT_ID: $(kv-client-id)
      AZURE_CLIENT_SECRET: $(kv-client-secret)
      FhirServerUrl: $(fhir-api-url)
      KeyVaultUri: $(proxy-key-vault-uri)
      KeyVaultCertificateName: $(proxy-key-vault-certificate-name)
      InstrumentationKey: $(proxy-instrumentation-key)
      LoggingLevel: $(proxy-log-level)
      StorageConnectionString: $(storage-connectionstring-test)
      StorageAccountName: $(storage-accountname-test)
      EventHubBlobConnectionString: $(proxy-storage-connectionstring)
      EventHubProcessorContainer: $(proxy-eventhub-processorcontainer-name)
      EventHubBlobContainer: $(proxy-eventhub-blobcontainer-name)
      EventHubBlobStorageAccountName: $(proxy-eventhub-blobstorageaccountname)
      EventHubSku: $(proxy-eventhub-sku)
      STORAGE_CONNECTIONSTRING: $(proxy-storage-connectionstring)
      EventHubNamespace: $(proxy-eventhub-namespace)
      EventHubName: $(proxy-eventhub-name)
      EventHubConnectionString: $(proxy-eventhub-connectionstring)
      ServiceBusConnectionString: $(proxy-servicebus-connectionstring)
      ServiceBusNamespace: $(proxy-servicebus-namespace)
      ServiceBusQueue: $(proxy-servicebus-queue)
      ServiceBusTopic: $(proxy-servicebus-topic)
      ServiceBusSubscription: $(proxy-servicebus-subscription)
      ServiceBusSku: $(proxy-servicebus-sku)
      ServiceBusBlobConnectionString: $(proxy-storage-connectionstring)
      ServiceBusBlobStorageAccountName: $(proxy-servicebus-blobstorageaccountname)
      ServiceBusBlobContainer: $(proxy-servicebus-blobcontainer-name)
      BlobStorageChannelConnectionString: $(proxy-storage-connectionstring)
      BlobStorageChannelContainer: $(proxy-blobchannel-container-name)
      BlobStorageAccountName: $(proxy-blobchannel-account-name)
      EventGridSubject: $(proxy-eventgrid-subject)
      EventGridEventType: $(proxy-eventgrid-eventtype)
      EventGridDataVersion: $(proxy-eventgrid-dataversion)
      EventGridTopicUriString: $(proxy-eventgrid-topicuristring)
      EventGridTopicAccessKey: $(proxy-eventgrid-topicaccesskey)
      EventGridBlobConnectionString: $(proxy-eventgrid-blobconnectionstring)
      EventGridBlobContainer: $(proxy-eventgrid-blobcontainer)
      EventGridBlobStorageAccountName: $(proxy-eventgrid-blobstorageaccountname)
      EventGrid_Message_Queue: $(eventgrid-message-queue)
      EventGrid_Reference_Queue: $(eventgrid-reference-queue)
      CacheConnectionString: $(cicd-redis-cache-connectionstring)
      CacheHostName: $(cicd-redis-cache-hostname)

  - script: |
      echo "TENANT: $AZURE_TENANT_ID"
      echo "CLIENT: $AZURE_CLIENT_ID"
    displayName: 'Echo Azure Auth Vars'
    env:
      AZURE_TENANT_ID: $(proxy-tenant-id)
      AZURE_CLIENT_ID: $(kv-client-id)